templates:
  First - Custom:
    optional:
      - sort_title
      - summary
    sort_title: '!_First <<collection_name>>'
    summary: <<summary>>
  'First [Sort Title] - Custom':
    optional:
      - list
      - name_mapping
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    name_mapping: <<name_mapping>>
    sort_title: '!_First <<sort_title>>'
    summary: <<summary>>
collections:
  All-Time Faves:
    template:
      name: 'First [Sort Title] - Custom'
      sort_title: '!8All-Time Faves'
      summary: >-
        These movies have earned their spot as your absolute favorites,
        guaranteed to always deliver the perfect blend of nostalgia and
        enjoyment every time.
    collection_filtering: user
    smart_filter:
      sort_by: title.asc
      any:
        all:
          user_rating.gte: 9.5
        any:
          label: Aaron
  Watchlist:
    template:
      name: 'First [Sort Title] - Custom'
      sort_title: '!7Watchlist'
      summary: >-
        Procrastination's Greatest Hits: Films too intimidating for a Tuesday,
        too cerebral for a Friday, and somehow never quite right for any time in
        between. Their runtime alone makes your eyelids heavy.
    plex_watchlist: added.desc
    collection_order: custom
    sync_mode: sync
  Aaron's Faves:
    build_collection: false
    trakt_list: 'https://trakt.tv/users/goape/lists/movies-aaron'
    item_label: Aaron
    sync_mode: append
    non_item_remove_label: Aaron
  Horror:
    build_collection: false
    trakt_list: 'https://trakt.tv/users/goape/lists/movies-horror'
    item_label: Horror
    sync_mode: append
    non_item_remove_label: Horror
