overlays:
  Bravo:
    overlay:
      name: Bravo
      file: config/overlays/Bravo/overlay-v2.png
    plex_search:
      all:
        label: Bravo
  Disney-Channel:
    overlay:
      name: Disney-Channel
      file: config/overlays/Disney-Channel/overlay-v2.png
    plex_search:
      all:
        label: Disney Channel
  History:
    overlay:
      name: History
      file: config/overlays/History/overlay-v2.png
    plex_search:
      all:
        label: History
  Pilot-Episodes:
    overlay:
      name: Pilot-Episodes
      file: config/overlays/Pilot-Episodes/overlay.png
    plex_search:
      all:
        label: 'First Impressions: Pilot Episodes Only'
  First-Season:
    overlay:
      name: First-Season
      file: config/overlays/First-Season/overlay.png
    plex_search:
      all:
        label: First Season
  New-Episodes:
    overlay:
      name: New-Episodes
      file: config/overlays/New-Episodes/overlay.png
    plex_search:
      type: shows
      all:
        episode_air_date: 7
        label.not:
          - First Season
          - 'First Impressions: Pilot Episodes Only'
